all:
  children:
    webservers:
      hosts:
        app-server-1:
          ansible_host: 95.174.92.129
          ansible_user: user1
          ansible_ssh_private_key_file: ~/.cloud-ru-key
        app-server-2:
          ansible_host: 176.109.100.190
          ansible_user: user1
          ansible_ssh_private_key_file: ~/.cloud-ru-key

    webservers:vars: ansible_python_interpreter=/usr/bin/python3
