db_host: "{{ vault_db_host }}"
db_name: "{{ vault_db_name }}"
db_user: "{{ vault_db_user }}"
db_password: "{{ vault_db_password }}"
db_port: "{{ vault_db_port }}"

redmine_port: 3000
redmine_image: redmine:5.1
redmine_container_name: redmine
